backlight: rpi-backlight: fix missing return in remove()
When building the rpi-backlight driver with clang, we have the following
build error:

    src/drivers/video/backlight/rpi_backlight.c:107:1:
    error: control reaches end of non-void function [-Werror,-Wreturn-type]

Fix it by adding a missing "return 0" in the remove() function.

Fixes: 38b79b207d33 ("backlight: add rpi-backlight driver")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>