BL_INTERNAL: media: mtk-mdp: fix compilation issue
Remove unused variables.

This fixes the following compilation issues:

mtk_mdp_core.c:126:6: error: unused variable 'wait_cnt' [-Werror,-Wunused-variable]
        int wait_cnt = 0, vcuid;
            ^
mtk_mdp_core.c:126:20: error: unused variable 'vcuid' [-Werror,-Wunused-variable]
        int wait_cnt = 0, vcuid;

Signed-off-by: Pierre Moos <pmoos@baylibre.com>