iommu/mediatek: Fix -Wbraced-scalar-init for MT8365
When building with -Werror, we have the following build error:

drivers/iommu/mtk_iommu.c:863:19: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
      .larbid_remap = {{0}, {1}, {2}, {3}, {4}, {5}}, /* Linear mapping. */

Fix it by removing the un-needed braces.

Note: this is un-needed for more recent kernels since those have
commit 37276e00da7d ("iommu/mediatek: Add sub_comm id in translation fault")

Fixes: 01023042ace0 ("iommu: mtk_iommu: Add MT8365 support")
Suggested-by: Guillaume La Roque <glaroque@baylibre.com>
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>