BL_INTERNAL: Revert "ANDROID: GKI: set vfs-only exports into their own namespace"
After updating kernel to version 5.10.104, building it generates
the following error:

ERROR: modpost: module wlan_drv_gen4_MT7668 uses symbol kernel_write from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module wlan_drv_gen4_MT7668 uses symbol kernel_read from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module wlan_drv_gen4_MT7668 uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

All vfs-exported namespaces were introduced in commit d483eed85ffb,
but they are not needed for Android kernel images.

This reverts commit d483eed85ffb9879b103cd8d6b3fae367fa6193e.

Signed-off-by: ￼Vitor Sato Eschholz <vsatoes@baylibre.com>