BL_INTERNAL: net: ethernet: mtk-star-emac: add missing bitfield.h include
Commit 4bab0eeeb3c2 ("net: ethernet: mediatek: add simple timing adjustment")
introduces the usage of the FIELD_PREP macro without including
linux/bitfield.h.

The compiler reports this with:

drivers/net/ethernet/mediatek/mtk_star_emac.c: In function ‘mtk_star_set_mac_delay’:
drivers/net/ethernet/mediatek/mtk_star_emac.c:1527:30: error: implicit declaration of function ‘FIELD_PREP’ [-Werror=implicit-function-declaration]
 1527 |                 delay_val |= FIELD_PREP(MTK_STAR_BIT_INV_TX_CLK, mac_delay->tx_inv);
      |                              ^~~~~~~~~~
cc1: some warnings being treated as errors

Fix the build warning by adding the include.

Fixes: 4bab0eeeb3c2 ("net: ethernet: mediatek: add simple timing adjustment")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>