FIXUP: FROMLIST: PM / AVS: SVS: Introduce SVS engine
0-day reports:

drivers/power/avs/mtk_svs.c:1785:21: sparse: sparse:
	symbol 'svs_mt8183_banks_ops' was not declared. Should it be static?
drivers/power/avs/mtk_svs.c:1790:17: sparse: sparse:
	symbol 'svs_mt8183_banks' was not declared. Should it be static?
drivers/power/avs/mtk_svs.c:420:15: sparse: sparse:
	context imbalance in 'claim_mtk_svs_lock' - wrong count at exit
drivers/power/avs/mtk_svs.c:430:6: sparse: sparse:
	context imbalance in 'release_mtk_svs_lock' - unexpected unlock

drivers/power/avs/mtk_svs.o: In function `svs_set_volts':
mtk_svs.c:(.text+0x1310): undefined reference to `thermal_zone_get_zone_by_name'
mtk_svs.c:(.text+0x131c): undefined reference to `thermal_zone_get_temp'
drivers/power/avs/mtk_svs.o: In function `svs_status_proc_show':
mtk_svs.c:(.text+0x2e48): undefined reference to `thermal_zone_get_zone_by_name'
mtk_svs.c:(.text+0x2e54): undefined reference to `thermal_zone_get_temp'

BUG=b:131870177
TEST=make, make C=2, make allmodconfig

Change-Id: Ic746b21fd9f1ba3017e947a59a22ea13f98fd135
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1810559
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>