BL_INTERNAL:phy: mediatek: remove unused variable 'pmipi_rx_base'
When building with -Werror, we have the following build error:

drivers/phy/mediatek/phy-mtk-cdphy.c:60:16:
error: unused variable 'pmipi_rx_base' [-Werror,-Wunused-variable]
        void __iomem *pmipi_rx_base = port->dev->rx;

Fix it by removing the unused variable.

Fixes: 967e15bbd597 ("phy: mediatek: Move cdphy driver to phy drivers' folder")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>