BL_INTERNAL: media: subdev: fix compilation issue
The ANDROID commit e0a95560412 has to be updated with the
the v4l2_subdev_fh structure udpate done in commit 63d8e50c26 where
"struct v4l2_subdev_pad_config *pad"
is replaced by
"struct v4l2_subdev_state *state"

This fixes the following error:
error: no member named 'pad' in 'struct v4l2_subdev_fh'

Signed-off-by: Pierre Moos <pmoos@baylibre.com>