BL_INTERNAL: media: mtk-vcodec-mt8167: fix compilation issues
Remove unused variables.

This fixes the following compilation issues:
mtk_vcodec_dec.c:640:25: error: unused variable 'dev' [-Werror,-Wunused-variable]
        struct mtk_vcodec_dev *dev = ctx->dev;
                               ^
mtk_vcodec_dec_drv.c:254:6: error: unused variable 'val' [-Werror,-Wunused-variable]
        int val = 0;
            ^
mtk_vcodec_dec_drv.c:253:6: error: unused variable 'wait_cnt' [-Werror,-Wunused-variable]
        int wait_cnt = 0;

mtk_vcodec_enc.c:1761:15: error: unused variable 'suspend_block_cnt' [-Werror,-Wunused-variable]
        unsigned int suspend_block_cnt = 0;

mtk-vcodec-mt8167/mtk_vcodec_enc_drv.c:245:6: error: unused variable 'wait_cnt' [-Werror,-Wunused-variable]
        int wait_cnt = 0;
            ^
mtk-vcodec-mt8167/mtk_vcodec_enc_drv.c:246:6: error: unused variable 'val' [-Werror,-Wunused-variable]
        int val = 0;

Signed-off-by: Pierre Moos <pmoos@baylibre.com>