ANDROID: MTK: misc: mediatek: rgx: add -Wno-typedef-redefinition
When building with -Werror, we have the following build warning:

> src/drivers/misc/mediatek/gpu/gpu_rgx/rita/m1.13.5878540/services/server/devices/rogue/rgxmem.c:85:3: warning:
>       redefinition of typedef 'SERVER_MMU_CONTEXT' is a C11 feature [-Wtypedef-redefinition]
> } SERVER_MMU_CONTEXT;
>   ^
> src/drivers/misc/mediatek/gpu/gpu_rgx/rita/m1.13.5878540/services/server/devices/rogue/rgxmem.h:67:37: note:
>       previous definition is here
> typedef struct _SERVER_MMU_CONTEXT_ SERVER_MMU_CONTEXT;

Since this is code dropped from imgtec and we really don't want to spend
time fixing it, add a -Wno-typedef-redefinition to work-around the build error.

Bug: RITA-577
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>