UPSTREAM_OR_FROMLIST: FIXUP: CHROMIUM: MALI: Add Mali platform specific source
Commit d12dc1a83564 ("CHROMIUM: MALI: Add Mali platform specific source")
introduced platform specific source introduces defines which are only
available for the mediatek platform. This results in build failures such as

drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:
	In function 'voltage_range_check':
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:84:44: error:
	'MIN_VOLT_BIAS' undeclared
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:86:44: error:
	'MAX_VOLT_BIAS' undeclared
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:89:24: error:
	'VSRAM_GPU_MAX_VOLT' undeclared

and so on for all other platforms, including the default "devicetree"
platform. Effectively, MALI_DEVFREQ is now broken for all Mali platforms
except Mediatek. Restrict its use accordingly.

With that fixed, arm64:allmodconfig still fails to build.

ERROR: "kbase_platform_dvfs_event" [drivers/gpu/arm/midgard/mali_kbase.ko]
	undefined!

This function is not defined anywhere, meaning MALI_MIDGARD_DVFS is
(and always was) broken as well. Mark it as such.

BUG=b:109911488
Test=Build arm64:allmodconfig

Change-Id: I73a75bd9da2a9fd7a5d96502ffdfd91ff5c780f0
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1384887
Commit-Ready: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>