HACK: ANDROID: MTK: mtk_android_defconfig: remove RGX_ANDROID_M1_13_5878540
RGX Android does not compile anymore after rebasing to 5.10

drivers/misc/mediatek/gpu/gpu_rgx/rita/m1.13.5878540/kernel/drivers/staging/imgtec/pvr_mtk_drv.c:45:10:
fatal error: 'drm/drmP.h' file not found
         ^~~~~~~~~~~~

As this driver is used only for i300a and android12 5.10 is not the main
target of this board and fixing RGX_ANDROID seems tedious work disable
it for now.

Signed-off-by: Guillaume Ranquet <granquet@baylibre.com>