BL_INTERNAL:input: touchscreen: edt-ft5x06: fix unused-variable warning
Fix the following error:

error: unused variable ‘client’ [-Werror=unused-variable]
  725 |  struct i2c_client *client = tsdata->client;
      |                     ^~~~~~

Signed-off-by: Fabien Parent <fparent@baylibre.com>