Revert "PM / devfreq: Add cpu based scaling support to passive_governor"
This reverts commit 7b273b5a1ba6d56388f2dd228181c48c93b609c1.

drivers/devfreq/governor_passive.c: In function ‘xlate_cpufreq_to_devfreq’:
drivers/devfreq/governor_passive.c:41:39: error: ‘struct devfreq’ has no member named ‘opp_table’
   41 |      !cpu_state->opp_table || !devfreq->opp_table)
      |                                       ^~
drivers/devfreq/governor_passive.c:49:8: error: implicit declaration of function ‘dev_pm_opp_xlate_required_opp’ [-Werror=implicit-function-declaration]
   49 |  opp = dev_pm_opp_xlate_required_opp(cpu_state->opp_table,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/devfreq/governor_passive.c:50:17: error: ‘struct devfreq’ has no member named ‘opp_table’
   50 |          devfreq->opp_table, p_opp);
      |                 ^~
drivers/devfreq/governor_passive.c: In function ‘cpufreq_passive_register’:
drivers/devfreq/governor_passive.c:352:21: error: ‘struct devfreq’ has no member named ‘opp_table’
  352 |   if (IS_ERR(devfreq->opp_table)) {
      |                     ^~

Missing some patches as dependencies...
7d8658ef65a4f OPP: Add function to look up required OPP's for a given OPP

Signed-off-by: Guillaume Ranquet <granquet@baylibre.com>