FIXUP: CHROMIUM: MALI: Add Mali platform specific source
0day says:

drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:
	In function 'set_voltages':
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_devfreq.c:164:25: error:
	format '%d' expects argument of type 'int', but argument 3 has type 'ssize_t

It doesn't really make sense to use ssize_t for the variable in question,
nor for the other variables in the same function. Use int instead.

BUG=b:109911488
Test=emerge-kukui sys-kernel/chromeos-kernel-4_19

Change-Id: Ie95ef8116ff797d16f83317820d576b9538b15cf
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1387364
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>