ASoC: mediatek: mt8183: remove unused variable rstc
sound/soc/mediatek/mt8183/mt8183-afe-pcm.c:1114:24: error: unused variable 'rstc' [-Werror,-Wunused-variable]

Signed-off-by: Guillaume Ranquet <granquet@baylibre.com>