misc: mediatek: remove unused function
drivers/misc/mediatek/usb11/mt8167/musbfsh_mt65xx.c:640:12: error: unused function 'mt_usb_remove' [-Werror,-Wunused-function]

Signed-off-by: Guillaume Ranquet <granquet@baylibre.com>