ASoC: mediatek: mt8365: remove unused variable
The driver does not build with -Werror:

sound/soc/mediatek/mt8365/mt8365-pumpkin.c:354:22:
error: unused variable 'np' [-Werror,-Wunused-variable]
        struct device_node *np = dev->of_node;
                                    ^

Fixes: c09f9cae7044 ("arm64: dts: mediatek: mt8365-pumpkin: Use a pumpkin specific soundcard")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>